# Generated by Django 6.0.3 on 2026-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('valor_raw', models.FloatField()),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('estado_procesamiento', models.BooleanField(default=False)),
                ('nivel_alerta', models.CharField(choices=[('NORMAL', 'Normal'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico')], default='NORMAL', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
