# Generated by Django 6.0.3 on 2026-06-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0001_initial'),
        ('robots', '0001_initial'),
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('estado_procesamiento', models.BooleanField(default=False)),
                ('nivel_alerta', models.CharField(choices=[('NORMAL', 'Normal'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico')], default='NORMAL', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misiones.mision')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor')),
            ],
        ),
    ]
