# Generated by Django 6.0.3 on 2026-05-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturas', '0001_initial'),
        ('misiones', '0001_initial'),
        ('robots', '0001_initial'),
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturasensor',
            name='mision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misiones.mision'),
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot'),
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor'),
        ),
    ]
