# Generated by Django 6.0.3 on 2026-05-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturasensor',
            name='valor',
        ),
    ]
