# Generated by Django 6.0.3 on 2026-05-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0003_remove_lecturasensor_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturasensor',
            old_name='valor_raw',
            new_name='valor',
        ),
    ]
