# Generated by Django 6.0.3 on 2026-06-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0001_initial'),
        ('robots', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Fotografía'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('NOTA_VOZ_TEXTO', 'Nota de voz transcrita')], max_length=20)),
                ('archivo', models.FileField(blank=True, upload_to='evidencias/')),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('tamanio_bytes', models.BigIntegerField(default=0)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misiones.mision')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.robot')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
    ]
