# Generated by Django 6.0.3 on 2026-05-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0004_remove_mision_usuario_mision_creado_por_and_more'),
        ('robots', '0002_delete_control'),
        ('usuarios', '0002_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Fotografía'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('NOTA_VOZ_TEXTO', 'Nota de voz transcrita')], max_length=20)),
                ('url_archivo', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('tamanio_bytes', models.BigIntegerField(default=0)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misiones.mision')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.robot')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
    ]
