# Generated by Django 6.0.3 on 2026-05-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='url_archivo',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(blank=True, upload_to='evidencias/'),
        ),
    ]
