# Generated by Django 6.0.3 on 2026-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico'), ('EMERGENCIA', 'Emergencia')], max_length=20)),
                ('tipo', models.CharField(choices=[('GAS_TOXICO', 'Gas tóxico'), ('INCENDIO', 'Incendio'), ('VOLCAMIENTO', 'Volcamiento del robot'), ('BATERIA_BAJA', 'Batería baja'), ('TEMPERATURA_ALTA', 'Temperatura alta'), ('DESCONEXION', 'Desconexión del robot'), ('VICTIMA_POSIBLE', 'Posible víctima detectada')], max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
                ('valor_detectado', models.FloatField()),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
