# Generated by Django 6.0.3 on 2026-06-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturas', '0001_initial'),
        ('misiones', '0001_initial'),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico'), ('EMERGENCIA', 'Emergencia')], max_length=20)),
                ('tipo', models.CharField(choices=[('GAS_TOXICO', 'Gas tóxico'), ('INCENDIO', 'Incendio'), ('VOLCAMIENTO', 'Volcamiento del robot'), ('BATERIA_BAJA', 'Batería baja'), ('TEMPERATURA_ALTA', 'Temperatura alta'), ('DESCONEXION', 'Desconexión del robot'), ('VICTIMA_POSIBLE', 'Posible víctima detectada')], max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
                ('valor_detectado', models.FloatField()),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturas.lecturasensor')),
                ('mision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misiones.mision')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
            ],
        ),
    ]
