# Generated by Django 6.0.3 on 2026-05-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='lectura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturas.lecturasensor'),
        ),
    ]
