# Generated by Django 6.0.3 on 2026-05-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISION', 'En misión'), ('MANTENIMIENTO', 'En mantenimiento'), ('AVERIADO', 'Averiado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=30)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('bateria_nivel', models.FloatField(default=0)),
                ('bateria_voltaje', models.FloatField(default=0)),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('horas_uso', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comando', models.CharField(choices=[('MOVER_ADELANTE', 'Mover adelante'), ('MOVER_ATRAS', 'Mover atrás'), ('GIRAR_IZQ', 'Girar izquierda'), ('GIRAR_DER', 'Girar derecha'), ('DETENER', 'Detener'), ('EMERGENCIA_STOP', 'Parada de emergencia'), ('TOMAR_FOTO', 'Tomar foto')], max_length=50)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('EJECUTADO', 'Ejecutado'), ('FALLIDO', 'Fallido')], default='ENVIADO', max_length=20)),
                ('latencia_ms', models.IntegerField(default=0)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('mision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misiones.mision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
            ],
        ),
    ]
