# Generated by Django 6.0.3 on 2026-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISION', 'En misión'), ('MANTENIMIENTO', 'En mantenimiento'), ('AVERIADO', 'Averiado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=30)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('bateria_nivel', models.FloatField(default=0)),
                ('bateria_voltaje', models.FloatField(default=0)),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('horas_uso', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
