# Generated by Django 6.0.3 on 2026-06-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='sede',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
