# Generated by Django 6.0.3 on 2026-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('token_push', models.CharField(blank=True, max_length=255)),
                ('token_sesion', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
