# Generated by Django 6.0.3 on 2026-05-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0004_remove_mision_usuario_mision_creado_por_and_more'),
        ('robots', '0002_delete_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetriaRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('velocidad', models.FloatField(default=0)),
                ('bateria_nivel', models.FloatField(default=0)),
                ('bateria_voltaje', models.FloatField(default=0)),
                ('inclinacion_lateral', models.FloatField(default=0)),
                ('inclinacion_frontal', models.FloatField(default=0)),
                ('modo_conduccion', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTONOMO', 'Autónomo')], default='MANUAL', max_length=20)),
                ('senal_rssi', models.IntegerField(default=0)),
                ('latencia_ms', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misiones.mision')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
            ],
        ),
    ]
