# Generated by Django 6.0.3 on 2026-06-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.CharField(choices=[('NORMAL', 'Normal'), ('PRECAUCION', 'Precaución'), ('ALTO_RIESGO', 'Alto riesgo'), ('CRITICO', 'Crítico')], max_length=20)),
                ('resumen', models.TextField()),
                ('victimas_fallecidas', models.IntegerField(default=0)),
                ('victimas_heridas', models.IntegerField(default=0)),
                ('victimas_rescatadas', models.IntegerField(default=0)),
                ('accion_recomendada', models.TextField(blank=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misiones.mision')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_generacion', models.CharField(choices=[('GENERANDO', 'Generando'), ('LISTO', 'Listo'), ('ERROR', 'Error')], default='GENERANDO', max_length=20)),
                ('url_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('victimas_fallecidas', models.IntegerField(default=0)),
                ('victimas_heridas', models.IntegerField(default=0)),
                ('victimas_rescatadas', models.IntegerField(default=0)),
                ('victimas_sin_confirmar', models.IntegerField(default=0)),
                ('duracion_minutos', models.IntegerField(default=0)),
                ('tiempo_respuesta_minutos', models.IntegerField(default=0)),
                ('tiempo_promedio_alerta_ms', models.IntegerField(default=0)),
                ('total_alertas', models.IntegerField(default=0)),
                ('alertas_criticas', models.IntegerField(default=0)),
                ('alertas_advertencia', models.IntegerField(default=0)),
                ('total_lecturas', models.IntegerField(default=0)),
                ('total_reportes_actualizacion', models.IntegerField(default=0)),
                ('nivel_riesgo_maximo', models.CharField(blank=True, max_length=20)),
                ('distancia_recorrida_m', models.FloatField(default=0)),
                ('bateria_inicio', models.FloatField(default=0)),
                ('bateria_fin', models.FloatField(default=0)),
                ('promedio_senal_rssi', models.FloatField(default=0)),
                ('total_snapshots_telemetria', models.IntegerField(default=0)),
                ('area_cubierta_m2', models.FloatField(default=0)),
                ('coordenadas_trayectoria', models.JSONField(default=list)),
                ('resumen_sensores', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('mision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='misiones.mision')),
            ],
        ),
    ]
