# Generated by Django 6.0.3 on 2026-05-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefinal',
            name='url_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
