# Generated by Django 6.0.3 on 2026-05-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GAS', 'Gas'), ('TEMPERATURA', 'Temperatura'), ('SONIDO', 'Sonido'), ('ULTRASONICO', 'Ultrasónico'), ('INFRARROJO', 'Infrarrojo'), ('IMU', 'IMU / Acelerómetro'), ('GPS', 'GPS')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=20)),
                ('umbral_critico', models.FloatField(blank=True, null=True)),
                ('calibracion_offset', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_lectura_valor', models.FloatField(blank=True, null=True)),
                ('ultima_lectura_fecha', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
            ],
        ),
    ]
