# Generated by Django 6.0.3 on 2026-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
