# Generated by Django 6.0.3 on 2026-05-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_sensor_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='calibracion_offset',
        ),
    ]
