# Generated by Django 6.0.3 on 2026-06-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('ABORTADA', 'Abortada')], default='PENDIENTE', max_length=30)),
                ('tipo', models.CharField(choices=[('DERRUMBE', 'Derrumbe'), ('INCENDIO', 'Incendio'), ('INUNDACION', 'Inundación'), ('EXPLOSION', 'Explosión'), ('FUGA_GAS', 'Fuga de gas'), ('PERSONA_PERDIDA', 'Persona perdida'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('zona_nombre', models.CharField(blank=True, max_length=150)),
                ('lat_zona', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng_zona', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('observaciones_admin', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones_creadas', to='usuarios.usuario')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones_operadas', to='usuarios.usuario')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.robot')),
            ],
        ),
    ]
