# Generated by Django 6.0.3 on 2026-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('ABORTADA', 'Abortada')], default='PENDIENTE', max_length=30)),
                ('tipo', models.CharField(choices=[('DERRUMBE', 'Derrumbe'), ('INCENDIO', 'Incendio'), ('INUNDACION', 'Inundación'), ('EXPLOSION', 'Explosión'), ('FUGA_GAS', 'Fuga de gas'), ('PERSONA_PERDIDA', 'Persona perdida'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('zona_nombre', models.CharField(blank=True, max_length=150)),
                ('lat_zona', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('lng_zona', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
