# Generated by Django 6.0.3 on 2026-05-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0001_initial'),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.robot'),
        ),
    ]
