# Generated by Django 6.0.3 on 2026-05-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misiones', '0003_mision_usuario_alter_mision_lat_zona_and_more'),
        ('usuarios', '0002_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mision',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mision',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones_creadas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='mision',
            name='observaciones_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mision',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones_operadas', to='usuarios.usuario'),
        ),
    ]
