# Generated by Django 6.0.3 on 2026-06-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSTRUCCION', 'Instrucción'), ('EVACUACION', 'Evacuación'), ('INFORMATIVO', 'Informativo'), ('CRITICO_AUTO', 'Crítico automático')], max_length=20)),
                ('contenido', models.TextField()),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('CRITICO', 'Crítico')], default='NORMAL', max_length=10)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('push_enviado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_recibidos', to='usuarios.usuario')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misiones.mision')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('ALERTA', 'Alerta de sensor'), ('REPORTE_CRITICO', 'Reporte crítico'), ('MENSAJE_ADMIN', 'Mensaje del admin'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=500)),
                ('token_push', models.CharField(max_length=255)),
                ('entregada', models.BooleanField(default=False)),
                ('respuesta_fcm', models.CharField(blank=True, max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misiones.mision')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
