# Generated by Django 6.0.3 on 2026-05-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misiones', '0004_remove_mision_usuario_mision_creado_por_and_more'),
        ('usuarios', '0002_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada', models.CharField(choices=[('NOTA', 'Nota'), ('EVENTO', 'Evento'), ('DECISION', 'Decisión'), ('HALLAZGO', 'Hallazgo'), ('INCIDENTE', 'Incidente')], default='NOTA', max_length=30)),
                ('contenido', models.TextField()),
                ('es_voz', models.BooleanField(default=False)),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misiones.mision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
    ]
